services:
  postgres:
    image: postgres:17.5
    container_name: postgres
    environment:
      POSTGRES_DB: bcc_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d bcc_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  movies-service:
    build:
      context: ./movies-service
    container_name: movies-service
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bcc_db
      SPRING_DATASOURCE_USERNAME: movies_user
      SPRING_DATASOURCE_PASSWORD: movies_pass
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  actors-service:
    build:
      context: ./actors-service
    container_name: actors-service
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bcc_db
      SPRING_DATASOURCE_USERNAME: actors_user
      SPRING_DATASOURCE_PASSWORD: actors_pass
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  pgdata:
networks:
  backend:
    driver: bridge