version: "3.8"
services:
  postgres:
    image: postgres:17.5
    container_name: postgres
    environment:
      POSTGRES_DB: bcc_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - backend
  movies-service:
    build:
      context: ./movies-service
    container_name: movies-service
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bcc_db
      SPRING_DATASOURCE_USERNAME: movies_user
      SPRING_DATASOURCE_PASSWORD: movies_pass
    depends_on:
      - postgres
    networks:
      - backend
  actors-service:
    build:
      context: ./actors-service
    container_name: actors-service
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bcc_db
      SPRING_DATASOURCE_USERNAME: actors_user
      SPRING_DATASOURCE_PASSWORD: actors_pass
    depends_on:
      - postgres
    networks:
      - backend
volumes:
  pgdata:
networks:
  backend:
    driver: bridge