spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bcc_db
    username: movies_user
    password: movies_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: movies

server:
  port: 8080
  address: 0.0.0.0

jwt:
  expiration: 86400000 # 24 hours in milliseconds

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
    enabled: true

logging:
  level:
    org.springframework.security: DEBUG
    si.src.bcc.movies: DEBUG