spring:
  application:
    name: MoviesService
  datasource:
    url: jdbc:postgresql://postgres:5432/bcc_db
    username: movies_user
    password: movies_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.default_schema: movies
  sql:
    init:
      mode: always