spring:
  application:
    name: ActorsService
  datasource:
    url: jdbc:postgresql://localhost:5432/bcc_db
    username: actors_user
    password: actors_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: actors

server:
  port: 8082

jwt:
  expiration: 86400000 # 24 hours in milliseconds

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
    enabled: true

logging:
  level:
    org.springframework.security: DEBUG
    si.src.bcc.actors: DEBUG