spring:
  application:
    name: ActorsService
  datasource:
    url: jdbc:postgresql://postgres:5432/bcc_db
    username: actors_user
    password: actors_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.default_schema: actors
  sql:
    init:
      mode: always